from __future__ import annotations

from pathlib import Path

from ide.models.table_definition import FieldDefinition, TableDefinition
from ide.services.workbench_service import WorkbenchService


class TableService:
    def __init__(self, workbench: WorkbenchService) -> None:
        self.workbench = workbench

    def list_tables(self) -> list[TableDefinition]:
        tables: list[TableDefinition] = []
        for file_path in sorted(self.workbench.tables_dir.glob('*.json')):
            tables.append(TableDefinition.from_dict(self.workbench.read_json(file_path, {})))
        return tables

    def get_table(self, name: str) -> TableDefinition | None:
        file_path = self.workbench.tables_dir / f"{name.lower()}.json"
        if not file_path.exists():
            return None
        return TableDefinition.from_dict(self.workbench.read_json(file_path, {}))

    def save_table(self, definition: TableDefinition) -> Path:
        file_path = self.workbench.tables_dir / f"{definition.name.lower()}.json"
        self.workbench.write_json(file_path, definition.to_dict())
        return file_path

    def delete_table(self, name: str) -> None:
        file_path = self.workbench.tables_dir / f"{name.lower()}.json"
        if file_path.exists():
            file_path.unlink()

    def generate_mint_definition(self, definition: TableDefinition) -> Path:
        generated_dir = self.workbench.generated_dir / "tables"
        generated_dir.mkdir(parents=True, exist_ok=True)
        file_path = generated_dir / f"{definition.name.lower()}.mint"
        struct_name = ''.join(part.capitalize() for part in definition.name.split('_'))
        lines = [f'" Auto-generated by Mint ERP Studio', f'struct {struct_name}.']
        for field in definition.fields:
            field_type = field.field_type or 'string'
            lines.append(f'  {field.name} type {field_type}.')
        lines.extend([
            'endstruct.',
            '',
            'program init.',
            f'  var {definition.name.lower()}_record type {struct_name}.',
            'initialization.',
            f'  write("Table definition ready: {definition.name}").',
            'endprogram.',
            '',
        ])
        file_path.write_text('\n'.join(lines), encoding='utf-8')
        definition.generated_code_path = str(file_path)
        self.save_table(definition)
        return file_path

    def ensure_example_table(self) -> None:
        if any(self.workbench.tables_dir.glob('*.json')):
            return
        sample = TableDefinition(
            name='erp_customer',
            description='Cadastro de clientes do ERP Mint.',
            module='sales',
            fields=[
                FieldDefinition(name='id', description='Identificador', field_type='uuid', required=True, primary_key=True),
                FieldDefinition(name='name', description='Nome do cliente', field_type='string', length='120', required=True),
                FieldDefinition(name='tax_id', description='Documento fiscal', field_type='char', length='14'),
                FieldDefinition(name='active', description='Cliente ativo', field_type='bool', default_value='true'),
            ],
        )
        self.save_table(sample)
        self.generate_mint_definition(sample)
